import magento_integration_app
from .models import Product

clothes_category = [
    'T-shirty',
    'Bluzy',
    'Spodnie',
    'Sukienki',
    'Kurtki',
    'Swetry',
    'Spódnice',
    'Garnitury',
    'Bielizna',
    'Obuwie',
    'Koszule',
    'Marynarki',
    'Płaszcze',
    'Rajstopy',
    'Skarpetki',
    'Koszulki polo',
    'Szorty',
    'Kombinezony',
    'Piżamy',
    'Stroje kąpielowe',
    'Akcesoria do ubrań',
    'Czapki',
    'Czapki z daszkiem',
    'Okulary przeciwsłoneczne',
    'Rękawiczki',
    'Paski',
    'Szaliki',
    'Kosmetyki do pielęgnacji ubrań',
    'Odzież sportowa',
    'Buty sportowe',
    'Torby i plecaki',
    'Biżuteria',
    'Zegarki',
]